#!/usr/bin/env python3
"""gen_fwhdr.py — embed QCA9377 firmware binaries as C++ byte arrays.

Reads the pinned firmware files and emits FwData.h with:
  static const unsigned char qca9377_firmware6_bin[];
  static const unsigned int  qca9377_firmware6_len;
  static const unsigned char qca9377_board2_bin[];
  static const unsigned int  qca9377_board2_len;
  static const unsigned char qca9377_board_bin[];
  static const unsigned int  qca9377_board_len;

Deterministic output (sorted files, fixed line width) so CI diffs stay clean.
Run from the repo root:  python3 skeleton/gen_fwhdr.py
"""
import hashlib
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
FW_DIR = os.path.join(HERE, "..", "firmware", "QCA9377", "hw1.0")

FILES = [
    ("firmware-6.bin", "qca9377_firmware6"),   # API 6 — what ath10k loads first
    ("board-2.bin",    "qca9377_board2"),
    ("board.bin",      "qca9377_board"),
]

LINE = 20  # bytes per emitted line


def emit_array(out, name, data):
    out.write(f"static const unsigned char {name}_bin[] = {{\n")
    for i in range(0, len(data), LINE):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i:i + LINE])
        out.write(f"    {chunk},\n")
    out.write("};\n")
    out.write(f"static const unsigned int {name}_len = {len(data)};\n\n")


def main() -> int:
    missing = [f for f, _ in FILES
               if not os.path.isfile(os.path.join(FW_DIR, f))]
    if missing:
        print("missing firmware files:", ", ".join(missing))
        print("fetch them per docs/FIRMWARE.md first")
        return 1

    out_path = os.path.join(HERE, "FwData.h")
    with open(out_path, "w") as out:
        out.write("/*\n"
                  " * FwData.h — QCA9377 firmware, embedded as byte arrays.\n"
                  " * GENERATED by skeleton/gen_fwhdr.py — do not edit.\n"
                  " *\n"
                  " * Firmware redistribution: firmware/QCA9377/hw1.0/notice_ath10k_firmware-5.txt\n"
                  " * (Qualcomm Atheros notice text, shipped in the linux-firmware tree).\n"
                  " */\n\n"
                  "#ifndef QCA9377_FwData_h\n"
                  "#define QCA9377_FwData_h\n\n"
                  "#include <stdint.h>\n\n"
                  "#ifdef __cplusplus\n"
                  "extern \"C\" {\n"
                  "#endif\n\n")
        for fname, sym in FILES:
            path = os.path.join(FW_DIR, fname)
            data = open(path, "rb").read()
            md5 = hashlib.md5(data).hexdigest()
            out.write(f"/* {fname}: {len(data)} bytes, md5 {md5} */\n")
            emit_array(out, sym, data)
        out.write("#ifdef __cplusplus\n"
                  "}\n"
                  "#endif\n\n"
                  "#endif /* QCA9377_FwData_h */\n")
    size = os.path.getsize(out_path)
    print(f"wrote {out_path} ({size} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
